<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    /*function createIterator(arr){
        var i = 0;//指针索引
        return{
            next:function(){
                return i < arr.length? {value:arr[i++],done:false}:{value:undefined,done:true};
            }
        }
    }
    let iterator1 = createIterator([1,2,3,4]);
    console.log(iterator1.next());
    console.log(iterator1.next());*/


    /*
        为了给各种数据结构提供统一的遍历接口
    */
    // let str = "abc";
    // let arr1 = [1,2,3,4];
    // let m1 = new Map({name:"zhangsan",age:20});
    // let s1 = new Set([1,2,3,4]);
    // /*普通对象无法直接使用遍历器遍历*/
    // let obj1 = {name:"zhangsan",age:20};
    // for(let i  of str){
    //     console.log(str);
    // }
    // for(let i of arr1){
    //     console.log(i);
    // }


    /*
        只需要查看数据是否具有Symbol.iterator属性，就可知道该数据结构是否可被遍历器遍历
    */
   /* let arr1 = [1,2,3];
    console.log(arr1[Symbol.iterator]);

    let str = "abcd";
    let obj = {};
    console.log(obj[Symbol.iterator]);*/


    let[head,...detail] = [1,2.3,4];
    console.log(detail);
</script>
<script>
    //生成器
    function* helloGenerator(){
        yield "hello";
        yield "world";
        yield "ending";
    }

    let iterator1 = helloGenerator();
    console.log(iterator1.next());
    console.log(iterator1.next());
    console.log(iterator1.next());


</script>
<script>
    let myiterator = {};
    myiterator[Symbol.iterator]=function* (){
        yield {name:"zhangsan"};
        yield {age:20};
        return ;
    }
    console.log([...myiterator]);
    for(let i of myiterator){
        console.log(i);
    }
</script>

<script>
    //Promise
    setTimeout(function(){
        console.log("world");
    },3000)
    cosnole.log("hello");
</script>
<script>
     //Promise将异步的操作写成同步执行的方式
     /*
        resolve是异步操作成功的时候的调用
        reject是异步操作失败的时候的调用
     */
    new Promise(function(resolve,reject){
        setTimeout(function(){
            console.log("world");
            console.log(val);
            resolve();//对应then（）的第一个函数，调用
        },3000)
    }).then(function(){
        //对应resolve
        console.log("hello");
        console.log(val);//报错，跳转catch
    },function(){
        //对应reject
    }).catch(function(e){
        //捕获异常
        console.log(e);
    }).finally(function(){
        //无论如何都会执行的
        console.log("finally执行结束");
    })
</script>
</html>